services:
  app:
    container_name: mono
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DEFAULT_API_KEY: ${DEFAULT_API_KEY}
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - data:/home/bun/app

volumes:
  data:
